# Generated by Django 5.2.17 on 2026-09-26 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_seen_at_user_tokens_valid_after_and_more'),
        ('classes', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present')], default='present', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('auto', 'Auto')], default='auto', max_length=20)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='classes.classcourse')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendance', to='institutions.institution')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-joined_at'],
                'indexes': [models.Index(fields=['institution', 'date'], name='accounts_st_institu_ca2773_idx'), models.Index(fields=['class_course', 'date'], name='accounts_st_class_c_4f1b2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'class_course', 'date'), name='unique_student_attendance_per_class_per_day')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('present', 'Present')], default='present', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendance', to='institutions.institution')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-first_seen_at'],
                'indexes': [models.Index(fields=['institution', 'date'], name='accounts_te_institu_2f48eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date'), name='unique_teacher_attendance_per_day')],
            },
        ),
    ]
