# Generated by Django 5.2.17 on 2026-09-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentattendance_teacherattendance'),
        ('classes', '0003_liveclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendance', to='classes.liveclass'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendance', to='classes.liveclass'),
        ),
    ]
