# Generated by Django 5.2.17 on 2026-10-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentattendance_live_class_and_more'),
        ('institutions', '0002_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(blank=True, help_text="Only meaningful for role='student'. Determines which subject-classes auto-enroll the student.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='institutions.grade'),
        ),
    ]
