# Generated by Django 5.2.17 on 2026-10-06 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, help_text='Who marked this record (null for auto-generated).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20),
        ),
    ]
