# Generated by Django 5.2.17 on 2026-10-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentattendance_marked_by_studentattendance_note_and_more'),
        ('classes', '0005_classcourse_grade'),
        ('institutions', '0002_grade'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentattendance',
            name='unique_student_attendance_per_class_per_day',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Set when attendance is recorded at the grade level (daily roll call).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='institutions.grade'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='class_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='classes.classcourse'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('class_course__isnull', False)), fields=('student', 'class_course', 'date'), name='unique_student_attendance_per_class_per_day'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('grade__isnull', False)), fields=('student', 'grade', 'date'), name='unique_student_attendance_per_grade_per_day'),
        ),
    ]
