# Generated by Django 5.2.17 on 2026-10-07 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_studentattendance_unique_student_attendance_per_class_per_day_and_more'),
        ('institutions', '0002_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGradeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='institutions.grade')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grade_assignments', to='institutions.institution')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='grade_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grade__level'],
                'indexes': [models.Index(fields=['teacher'], name='accounts_te_teacher_656e4b_idx'), models.Index(fields=['grade'], name='accounts_te_grade_i_a46412_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'grade'), name='unique_teacher_per_grade')],
            },
        ),
    ]
