# Generated by Django 5.2.17 on 2026-10-08 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_teachergradeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(db_index=True, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student credentials',
                'indexes': [models.Index(fields=['pin'], name='accounts_st_pin_b6d32b_idx'), models.Index(fields=['is_active'], name='accounts_st_is_acti_6f8862_idx')],
            },
        ),
    ]
