import { http, HttpResponse } from "msw";

import { findUserById } from "../data/users";
import {
  appendMessage,
  canAccessThread,
  findThreadById,
  markThreadRead,
  messagesForThread,
  serializeMessage,
  serializeThread,
  threadsForUser,
} from "../data/chat";
import { getBearerToken, userIdForAccessToken } from "../data/session";
import { simpleError, unauthorized, validationError } from "../utils";

const BASE = "/api/v1";

function currentUser(request) {
  const token = getBearerToken(request);
  const userId = token ? userIdForAccessToken(token) : null;
  return userId ? findUserById(userId) : null;
}

export const chatHandlers = [
  // GET /chat/threads/ -- every thread the caller participates in.
  // Direct threads: the caller is a participant.
  // Group threads: the caller is the class teacher OR an active student.
  http.get(`${BASE}/chat/threads/`, ({ request }) => {
    const user = currentUser(request);
    if (!user) return unauthorized();

    const list = threadsForUser(user.id).map((t) => serializeThread(t, user.id));
    // Sort by most-recent activity; threads with no messages sort last.
    list.sort((a, b) => {
      const aTime = a.last_message ? new Date(a.last_message.created_at) : 0;
      const bTime = b.last_message ? new Date(b.last_message.created_at) : 0;
      return bTime - aTime;
    });
    return HttpResponse.json(list);
  }),

  // GET /chat/threads/:id/messages/ -- message history for one thread.
  http.get(`${BASE}/chat/threads/:id/messages/`, ({ request, params }) => {
    const user = currentUser(request);
    if (!user) return unauthorized();
    if (!canAccessThread(params.id, user.id)) {
      return simpleError("You do not have access to this thread.", 403);
    }

    const list = messagesForThread(params.id).map(serializeMessage);
    return HttpResponse.json(list);
  }),

  // POST /chat/threads/:id/messages/ -- send a message
  http.post(`${BASE}/chat/threads/:id/messages/`, async ({ request, params }) => {
    const user = currentUser(request);
    if (!user) return unauthorized();
    if (!canAccessThread(params.id, user.id)) {
      return simpleError("You do not have access to this thread.", 403);
    }

    const thread = findThreadById(params.id);
    if (!thread) return simpleError("Not found.", 404);

    const body = await request.json();
    if (!body.body || !String(body.body).trim()) {
      return validationError({ body: ["Message cannot be empty."] });
    }

    const message = appendMessage({
      threadId: thread.id,
      senderId: user.id,
      body: String(body.body).trim(),
    });

    return HttpResponse.json(serializeMessage(message), { status: 201 });
  }),

  // POST /chat/threads/:id/read/ -- mark every message as read by the caller.
  // Called by the frontend when the user opens a thread.
  http.post(`${BASE}/chat/threads/:id/read/`, ({ request, params }) => {
    const user = currentUser(request);
    if (!user) return unauthorized();
    if (!canAccessThread(params.id, user.id)) {
      return simpleError("You do not have access to this thread.", 403);
    }

    const changed = markThreadRead(params.id, user.id);
    return HttpResponse.json({ marked: changed });
  }),

  // DEV-ONLY: simulate an incoming message from the OTHER side of a thread.
  // Used by useMockSocket to make the UI feel live without a real WebSocket.
  // Body: { sender_id? } -- defaults to a random participant who isn't the
  // caller. Body text is generated by the caller.
  http.post(`${BASE}/__mock-incoming-message/`, async ({ request }) => {
    const user = currentUser(request);
    if (!user) return unauthorized();

    const payload = await request.json();
    const thread = findThreadById(payload.thread_id);
    if (!thread) return simpleError("Not found.", 404);

    // Pick a sender other than the caller. For group threads, prefer the
    // teacher; for direct threads, the other participant.
    let senderId = null;
    if (thread.kind === "group") {
      const { findClassById } = await import("../data/classes");
      const cls = findClassById(thread.class_id);
      senderId = cls?.teacher_id;
    } else {
      senderId = thread.participant_ids.find((id) => id !== user.id);
    }
    if (!senderId) return simpleError("No valid sender for this thread.", 400);

    const message = appendMessage({
      threadId: thread.id,
      senderId,
      body: String(payload.body || "").trim() || "(empty)",
    });
    return HttpResponse.json(serializeMessage(message), { status: 201 });
  }),
];
