# Generated by Django 5.2.17 on 2026-10-05 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(help_text='Numeric year level: 1, 2, ..., 12.')),
                ('name', models.CharField(help_text="Display name, e.g. 'Class 5' or 'Grade 5'.", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='institutions.institution')),
            ],
            options={
                'ordering': ['institution', 'level'],
                'indexes': [models.Index(fields=['institution', 'level'], name='institution_institu_f8f0d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'level'), name='unique_grade_level_per_institution')],
            },
        ),
    ]
