# Generated by Django 5.2.17 on 2026-09-15 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Archived = read-only but still visible. Distinct from is_deleted (soft-delete).')),
                ('institution', models.ForeignKey(blank=True, help_text='Nullable until Module J (Institution Management) exists — a self-registered teacher has no institution to attach yet. Once Module J ships, backfill this and consider making it required.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='institutions.institution')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joining_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked'), ('removed', 'Removed')], default='pending', max_length=10)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.classcourse')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='classcourse',
            index=models.Index(fields=['teacher'], name='classes_cla_teacher_ff83ee_idx'),
        ),
        migrations.AddIndex(
            model_name='classcourse',
            index=models.Index(fields=['institution'], name='classes_cla_institu_79239b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['joining_code'], name='classes_stu_joining_2726cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'class_course'), name='unique_student_per_class'),
        ),
    ]
