# Generated by Django 5.2.17 on 2026-09-26 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag. Inactive rows are hidden from the UI.')),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='classes.classcourse')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='institutions.institution')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['institution', 'day_of_week'], name='classes_tim_institu_a8f699_idx'), models.Index(fields=['teacher', 'day_of_week'], name='classes_tim_teacher_09b061_idx'), models.Index(fields=['class_course', 'day_of_week'], name='classes_tim_class_c_60f984_idx')],
                'constraints': [models.UniqueConstraint(fields=('class_course', 'day_of_week', 'start_time'), name='unique_timetable_class_slot')],
            },
        ),
    ]
