# Generated by Django 5.2.17 on 2026-09-26 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_timetableentry'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField()),
                ('room', models.CharField(blank=True, default='', max_length=100)),
                ('stored_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('meeting_url', models.URLField(blank=True, default='')),
                ('recording_url', models.URLField(blank=True, default='')),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='classes.classcourse')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='institutions.institution')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes_teaching', to=settings.AUTH_USER_MODEL)),
                ('timetable_entry', models.ForeignKey(help_text='Recurring slot this session was materialized from.', on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='classes.timetableentry')),
            ],
            options={
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['institution', 'scheduled_date'], name='classes_liv_institu_ac0aef_idx'), models.Index(fields=['teacher', 'scheduled_date'], name='classes_liv_teacher_4709f7_idx'), models.Index(fields=['class_course', 'scheduled_date'], name='classes_liv_class_c_d774c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('timetable_entry', 'scheduled_date'), name='unique_live_class_per_slot_per_day')],
            },
        ),
    ]
