# Generated by Django 5.2.17 on 2026-10-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_material'),
        ('institutions', '0002_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcourse',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Optional grade/standard this class is taught at. If set, all students in that grade auto-enroll.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_courses', to='institutions.grade'),
        ),
    ]
