# Generated by Django 5.2.17 on 2026-10-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classcourse_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, help_text='Optional human-readable roll number (e.g. STU-2026-001, or just 01).', max_length=32),
        ),
    ]
