# Generated by Django 5.2.17 on 2026-10-09 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_studentenrollment_roll_number'),
        ('institutions', '0002_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('class_course', models.ForeignKey(blank=True, help_text="Null = announcement targets all of this teacher's classes.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.classcourse')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='institutions.institution')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher'], name='classes_ann_teacher_97ae8b_idx'), models.Index(fields=['class_course'], name='classes_ann_class_c_3c3db3_idx'), models.Index(fields=['-created_at'], name='classes_ann_created_178474_idx')],
            },
        ),
    ]
