# Generated by Django 5.2.17 on 2026-09-22 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION audit_log_reject_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_no_update
    BEFORE UPDATE ON core_auditlog
    FOR EACH ROW EXECUTE FUNCTION audit_log_reject_mutation();

CREATE TRIGGER audit_log_no_delete
    BEFORE DELETE ON core_auditlog
    FOR EACH ROW EXECUTE FUNCTION audit_log_reject_mutation();
"""

TRIGGER_DROP_SQL = """
DROP TRIGGER IF EXISTS audit_log_no_update ON core_auditlog;
DROP TRIGGER IF EXISTS audit_log_no_delete ON core_auditlog;
DROP FUNCTION IF EXISTS audit_log_reject_mutation();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_type", models.CharField(max_length=20)),
                ("action", models.CharField(db_index=True, max_length=80)),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["-occurred_at"], name="core_auditl_occurre_b98bab_idx"
                    ),
                    models.Index(
                        fields=["institution", "-occurred_at"],
                        name="core_auditl_institu_59185d_idx",
                    ),
                    models.Index(
                        fields=["actor", "-occurred_at"],
                        name="core_auditl_actor_i_a7144a_idx",
                    ),
                    models.Index(
                        fields=["action", "-occurred_at"],
                        name="core_auditl_action_14ede5_idx",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=TRIGGER_SQL,
            reverse_sql=TRIGGER_DROP_SQL,
        ),
    ]
