# Generated by Django 5.2.17 on 2026-09-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
